### ISSUE TITLE
zone_load function returns error when zone.load df has time column

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#22]

**Comment by bradystoll** [comment]
Just curious, I think this is fixed in the release_V2 branch, but could you check with your data? The zone_load function is substantially different now, so I want to make sure that isn't an issue there either.

**Comment by claytonpbarrows** [comment]
total.zone.load[,names(total.zone.load)!='time']=='ERROR'  doesn't work if total.zone.load is "ERROR"
