### ISSUE TITLE
z.load and r.load are in MWh instead of GWh

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#24]
it looks like this is due to https://github.com/NREL/MAGMA/blob/7cf3c6008704582e01d3332a8cf102d8549c0c15/setup_dataQueries.R#L140

**Comment by claytonpbarrows** [comment]
637cf3807b19a1bff617d5ce5569f77b0e330b85

**Comment by oconnellm** [comment]
Thanks for catching this. Makes sense because of the interval query. 

The summarise is only needed for the interval region data, although I guess it can't hurt to keep it for all the rest? The annual data is reported in the rplexos query as a sum already, so these are unnecessary lines of code.
