### ISSUE TITLE
curtailment is calculated wrong

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#26]
This line sums curtailment multiplied by the number of RE technologies defined for curtailment calculations:

https://github.com/NREL/MAGMA/blob/1e67501a5c499be16d42573bf18754a03c69dc43/source_scripts/t_annual_generation.R#L27

**Comment by claytonpbarrows** [comment]
the release_V2 branch calculates correctly. this can be closed upon merge

**Comment by bradystoll** [comment]
Fixed in 8c004ee2fe571bdfd8ae0da85ef6b079ddb0b6bd
