### ISSUE TITLE
DA-RT committed capacity plots error in RT committed capacity

### ISSUE THREAD

**Issue by oconnellm** [NREL/MAGMA#28]
RT committed capacity reports "Available Capacity", which is not correct because this does not take into account de-committed generators.

**Comment by bradystoll** [comment]
Fixed by multiplying "Available Capacity" by whether or not the units are committed. Fixed finally in 74044c5f156adfebb524ca5d8d1e9bc3f2c4896e, which just multiplies by a boolean of if "Units Generating" is greater than 0, as Available Capacity apparently accounts for the number of units already.
