### ISSUE TITLE
zone names assigned incorrectly when not providing mapping csv file 

### ISSUE THREAD

**Issue by oconnellm** [NREL/MAGMA#38]
if not providing a gen name to region and zone mapping file, the rplexos query query_generator returns generator name, region, and zone. But zone returned is actually the region category. Fix this by getting the region and zone attached to each node, then joining this zone mapping to the gen name and region returned from query_generator

**Comment by bradystoll** [comment]
This is actually an issue with rplexos, when it creates the SQLite database, it assigns zone names from the Region Category property, not the Zone name property. d7f6d824678e6bc1ee17b9f7b39cb0e5eb7a2f19 adds a warning message about this behavior and points to the python script tools/make_region_zone_csv.py, which will create the generator - region - zone mapping file from the input xml database.
