### ISSUE TITLE
warning message on reassign.zones

### ISSUE THREAD

**Issue by aliehlen1** [NREL/MAGMA#42]
`In addition: Warning message:
In if (reassign.zones == TRUE | as.character(total.zone.load) ==  :
  the condition has length > 1 and only the first element will be used`

That warning message happens every time I run because total.zone.load is not a single-element object. It doesn't change results (as far as I can tell).

**Comment by bradystoll** [comment]
fixed with ff6ee7bd643b5689bd4095a0a6dcac08f2de9335
