### ISSUE TITLE
add an input_data.csv for comparison

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#43]
I'm looking for an example input_data csv to produce the comparison figures.

**Comment by bradystoll** [comment]
Will do. For now, the only difference is that you add more rows in the database column for the different databases to compare. 

You can also add a 'reference scenario' column if you want to specify that, but I believe it takes the first scenario by default if you don't add that column

**Comment by claytonpbarrows** [comment]
If I add gen-region-zone-mapping and gen-type-file-location definitions for each scenario in the comparison, will it use them? Or, do I need to combine all the different files into a single one?

**Comment by bradystoll** [comment]
It assumes the same file is applicable to all scenarios. So, yes, combine them. If you want it to do the combining, that would be feasible. To use different mappings would be harder (i.e., if generator A maps to Region A in one scenario, but Region B in another scenario)

**Comment by claytonpbarrows** [comment]
I'm not moving generators around between scenarios, but I also don't have a single file that maps every gen in every scenario to zones/regions. I'll write a quick script to combine the files and add it as an option to run...

**Comment by bradystoll** [comment]
Awesome, sounds great

**Comment by bradystoll** [comment]
Fixed in 0cf627b74fc74d4e52a10146a991572b82539c3b and input example added in 1f02d2e36f7c986ab059cc453b273916483eb728
