### ISSUE TITLE
total reserve provision query fails

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#46]
the "Provision" property that can be used to calculate total reserve provision can exist in a number of places. Modify  the total_gen_reserve_provision function to be more flexible and be able to query Reserve.Generators and Reserve for Provision.

**Comment by bradystoll** [comment]
This is actually needed by generator type to make the reserves provision by generator plots (plot 21). So, we do need this as Reserve.Generators

**Comment by bradystoll** [comment]
Changed back with 4e551530f2d09dfb38755b242c95705276600137. Clayton is just going to add that as a new output
