### ISSUE TITLE
curtailment comparison figures plot twice for each chunk

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#48]

**Comment by bradystoll** [comment]
One of the two plots should be a diff from the reference scenario. If your ref scenario doesn't have curtailment though, it would look like the same plot twice. Should I make a second header to make that more clear? Or are you seeing something else?

**Comment by claytonpbarrows** [comment]
You're right, the second is a diff. However, it should have a Y-axis label of "Difference in Curtailment:

**Comment by bradystoll** [comment]
Fixed with 48a1431e682c26cf857ca443e0be8fc803d5d92f
