### ISSUE TITLE
Total Gen in Comparison (Table 12) calculates % from total sum over all scenarios

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#50]
Instead, % should be relative to each scenario...

| scenario  | Type          | GWh        | Percent |
|-----------|---------------|------------|---------|
| Base Case | Coal          | 76,832.42  | 13.02   |
| BR30      | Coal          | 63,632.98  | 10.78   |
| BR50      | Coal          | 46,069.62  | 7.81    |
| lowTX30   | Coal          | 62,548.02  | 10.60   |
| lowTx50   | Coal          | 44,796.64  | 7.59    |
| Base Case | Geothermal    | 11,736.05  | 1.99    |
| BR30      | Geothermal    | 11,731.21  | 1.99    |
| BR50      | Geothermal    | 10,985.19  | 1.86    |
| lowTX30   | Geothermal    | 11,730.02  | 1.99    |
| lowTx50   | Geothermal    | 11,049.82  | 1.87    |
| Base Case | Hydro         | 3,429.16   | 0.58    |
| BR30      | Hydro         | 3,443.52   | 0.58    |
| BR50      | Hydro         | 3,208.77   | 0.54    |
| lowTX30   | Hydro         | 3,442.91   | 0.58    |
| lowTx50   | Hydro         | 3,195.72   | 0.54    |
| Base Case | Gas CC        | 20,067.98  | 3.40    |
| BR30      | Gas CC        | 16,755.25  | 2.84    |
| BR50      | Gas CC        | 13,365.90  | 2.26    |
| lowTX30   | Gas CC        | 17,896.22  | 3.03    |
| lowTx50   | Gas CC        | 13,493.60  | 2.29    |
| Base Case | Biomass       | 289.13     | 0.05    |
| BR30      | Biomass       | 288.23     | 0.05    |
| BR50      | Biomass       | 283.53     | 0.05    |
| lowTX30   | Biomass       | 290.10     | 0.05    |
| lowTx50   | Biomass       | 284.45     | 0.05    |
| Base Case | Diesel/Bunker | 2,851.39   | 0.48    |
| BR30      | Diesel/Bunker | 1,219.14   | 0.21    |
| BR50      | Diesel/Bunker | 485.75     | 0.08    |
| lowTX30   | Diesel/Bunker | 1,228.01   | 0.21    |
| lowTx50   | Diesel/Bunker | 514.76     | 0.09    |
| lowTX30   | Wind          | 8,232.68   | 1.39    |
| BR30      | Wind          | 8,232.95   | 1.39    |
| BR50      | Wind          | 16,828.35  | 2.85    |
| lowTx50   | Wind          | 17,078.22  | 2.89    |
| Base Case | Wind          | 1,811.95   | 0.31    |
| lowTX30   | PV            | 12,567.98  | 2.13    |
| BR30      | PV            | 12,633.24  | 2.14    |
| BR50      | PV            | 26,721.82  | 4.53    |
| lowTx50   | PV            | 27,543.79  | 4.67    |
| Base Case | PV            | 906.38     | 0.15    |
| Base Case | Storage       | 59.69      | 0.01    |
| BR30      | Storage       | 43.31      | 0.01    |
| BR50      | Storage       | 169.39     | 0.03    |
| lowTX30   | Storage       | 41.24      | 0.01    |
| lowTx50   | Storage       | 201.05     | 0.03    |
| Base Case | Total         | 117,984.15 | 19.99   |
| BR30      | Total         | 117,979.85 | 19.99   |
| BR50      | Total         | 118,118.31 | 20.01   |
| lowTX30   | Total         | 117,977.19 | 19.99   |
| lowTx50   | Total         | 118,158.06 | 20.02   |
| Base Case | Curtailment   | 0.42       | 0.00    |
| BR30      | Curtailment   | 241.89     | 0.18    |
| BR50      | Curtailment   | 2,728.47   | 2.02    |
| lowTX30   | Curtailment   | 265.41     | 0.20    |
| lowTx50   | Curtailment   | 1,214.75   | 0.91    |

**Comment by bradystoll** [comment]
Fixed with 48a1431e682c26cf857ca443e0be8fc803d5d92f
