### ISSUE TITLE
make the zone/region order consistent and configurable

### ISSUE THREAD

**Issue by claytonpbarrows** [NREL/MAGMA#57]
From Philippines GMC:

In general and particularly in “2. Zonal Generation”, there are some inconsistencies in the arrangement of the x-axis labels (e.g. there are figures that have “BaseCase-BR30-BR50-lowTX30-lowTX50” and there are some that have “BaseCase-BR30-lowTX30-BR50-lowTX50”)

**Comment by bradystoll** [comment]
Fixed with f62fb0d5669f397089a64ac62963886f26317a76
