### ISSUE TITLE
total gen diff, zone gen diff, region gen diff legend order

### ISSUE THREAD

**Issue by oconnellm** [NREL/MAGMA#78]
Total gen diff and zone gen diff legend order is very mixed up compared to non-diff plots. 

Region gen diff legend is correct order just reversed from non-diff plots.

**Comment by bradystoll** [comment]
This is actually from the behavior of ggplot with + and - values. I think it tries to order the factors of the - values first and then the + ones, but I'm not sure.

**Comment by bradystoll** [comment]
Fixed with 2fb2ece51c396e21dcb1c0860ba2f364ea632a9d, though now the plots have all categories in gen.order, regardless of if they show up in the plot. If we want to change that, we should open a separate issue for it
