### ISSUE TITLE
getting an error when running sections 30 and 31 and not specifying DA database

### ISSUE THREAD

**Issue by oconnellm** [NREL/MAGMA#90]
DA database is NULL and when trying to run sections 30 and 31 I'm getting an error and the report doesn't get generated. The error seems to be related to the plotting function:
Quitting from lines 12-28 (HTML_output.Rmd) 
Quitting from lines NA-168 (HTML_output.Rmd) 
Error in element_text(face = 1, size = rel(0.8), face = "bold") : 
  formal argument "face" matched by multiple actual arguments

**Comment by claytonpbarrows** [comment]
Sorry, this was my fault. I'll fix today.
